POST http://localhost:8080/api/auth/invite
Content-Type: application/json

{
  "email": "employee3@company.com",
  "fullName": "Владимир Ручкин",
  "workspaceId": null,
  "roleId": 3,
  "inviterId": 4
}