spring.application.name=tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/имя_твоей_базы
spring.datasource.username=postgres
spring.datasource.password=твой_пароль
spring.jpa.hibernate.ddl-auto=update